spring:
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
      database: library
      port: 27017
      host: localhost
#      port: 0

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.library.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local